---
- hosts: docker_nodes
  roles:
    - go
    - docker-swarm

- hosts: loadbalancers
  vars_files:
    - inventory/docker_services.yml
  roles:
    - haproxy
    - { role: keepalived, keepalived_shared_ip: "10.1.43.200", keepalived_shared_iface: "eth1" }

- hosts: consul_nodes
  roles:
    - { role: consul, consul_group_name: "consul_nodes" }

- hosts: monitors
  become: yes
  become_user: root
  tasks:
    - name: Add yumrepo
      yum_repository: name=Grafane baseurl=https://packagecloud.io/grafana/stable/el/7/x86_64 gpgcheck=no description=Grafanarepo
- hosts: monitors
  become: yes
  become_user: root
  roles:
    - prometheus
    - grafana

  vars:
    prometheus_components: [ "prometheus" ]
    prometheus_conf_main: "template/prometheus.yml.j2"
- hosts: all
  become: yes
  become_user: root
  roles:
    - prometheus

  vars:
    prometheus_components: [ "node_exporter" ]
- include: services.yml
