---
- hosts: docker_nodes
  roles:
    - go
    - docker-swarm

- hosts: loadbalancers
  vars_files:
    - inventory/docker_services.yml
  roles:
    - haproxy
    - keepalived

- include: services.yml
