---
- hosts: managers
  roles:
    - { role: docker-swarm, docker_role: 'manager' }

- hosts: workers
  roles:
    - { role: docker-swarm, docker_role: 'worker' }

- hosts: loadbalancers
  vars_files:
    - inventory/docker_services.yml
  roles:
    - haproxy
    - keepalived

- include: services.yml
