---
- hosts: managers
  roles:
    - docker
    - docker_manager

- hosts: workers
  roles:
    - docker
    - docker_worker

- hosts: loadbalancers
  vars_files:
    - inventory/docker_services.yml
  roles:
    - ansible-haproxy

- include: services.yml
